mySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_auth.urls', namespace='user_auth')),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls")),
    path('playerTrainingSystem/', include('playerTrainingSystem.urls', namespace='playerTrainingSystem')),
]

playerTrainingSystem/urls.py
from django.urls import path
from . import views

app_name = 'playerTrainingSystem'
urlpatterns = [
    path('', views.index, name='manage_players'),
    path('eligible_players/', views.eligible_players, name='eligible_players'),
    path('create_player/', views.createPlayer, name='create_player'),
    path('update_player/<int:pk>', views.updatePlayer, name='update_player'),
    path('delete_player/<int:pk>', views.deletePlayer, name='delete_player'),
]

playerTrainingSystem/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
    """
    A model representing a player in a sports team.

    Inherits from Django's Model class and defines the fields of the player object.

    :param models.Model: A built-in Django class that represents a database table and its associated fields.
    :type models.Model: class
    """
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    skill_level = models.IntegerField(default=0)
    eligible_for_selection = models.BooleanField() 

def __str__(self):
    """
    Returns a string representation of the player object.

    :return: A string representation of the player object, consisting of the player's first name.
    :rtype: str
    """
    return self.first_name

playerTrainingSystem/forms.py
from django.forms import ModelForm
from .models import Player

"""
    A form used for creating and updating player objects.

    Inherits from Django's ModelForm class and uses the Player model to define the form fields.

    :param ModelForm: A built-in Django form class that creates a form based on a specified model.
    :type ModelForm: class
    """

class PlayerForm(ModelForm):
    """
        Metadata for the PlayerForm class.

        Specifies that the form should be based on the Player model and should include only the first_name, last_name,
        skill_level, and eligible_for_selection fields.

        :param model: The model that the form should be based on.
        :type model: Model
        :param fields: The fields that should be included in the form.
        :type fields: list
        """
    class Meta:
        model = Player
        fields = ['first_name', 'last_name', 'skill_level', 'eligible_for_selection']

playerTrainingSystem/views.py
from django.shortcuts import render, redirect
from .models import Player
from .forms import PlayerForm

# Create your views here.
def index(request):
    """
    Renders a view that displays a list of all player objects.

    Retrieves all player objects from the database using the Player.objects.all() method and passes them as a context
    dictionary to the 'manage_players.html' template. The template is then rendered using the render() function.

    :param request: The HTTP request object.
    :type request: HttpRequest
    :return: The HTTP response object containing the rendered template.
    :rtype: HttpResponse
    """
    players = Player.objects.all()
    context = {'players': players}
    return render(request, 'manage_players.html', context)

def eligible_players(request):
    """
    Renders a view that displays a list of eligible player objects.

    Retrieves all player objects from the database using the Player.objects.all() method, filters them to include only
    those that are eligible for selection, and passes them as a context dictionary to the 'view_players.html' template.
    The template is then rendered using the render() function.

    :param request: The HTTP request object.
    :type request: HttpRequest
    :return: The HTTP response object containing the rendered template.
    :rtype: HttpResponse
    """
    players = Player.objects.all()
    context = {'players': players}
    return render(request, 'view_players.html', context)

def createPlayer(request):
    """
    Creates a new player object using data submitted through a form.

    Renders a form using the PlayerForm class and handles POST requests to create a new player object based on the
    submitted data. If the request is not a POST request, the form is rendered as a blank form.

    :param request: The HTTP request object.
    :type request: HttpRequest
    :return: The HTTP response object containing the rendered form.
    :rtype: HttpResponse
    """
    form = PlayerForm()
    if request.method == 'POST':
        form = PlayerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('playerTrainingSystem:manage_players')
    context = {'form': form}
    return render(request, 'player_form.html', context)

def updatePlayer(request, pk):
    """
    Renders a view that displays a form for updating an existing player object.

    Retrieves the player object with the specified id from the database using the Player.objects.get() method, and
    creates a form instance for that player using the PlayerForm() class. If the request method is POST, the form is
    updated with the submitted data using the same PlayerForm() class, validated, and saved to the database using the
    form.save() method. If the form is valid, the view redirects to the 'manage_players' view. If the request method
    is GET, the view renders the player_form.html template with the form instance as context.

    :param request: The HTTP request object.
    :type request: HttpRequest
    :param pk: The id of the player object to be updated.
    :type pk: int
    :return: The HTTP response object containing the rendered template.
    :rtype: HttpResponse
    """
    player = Player.objects.get(id=pk)
    form = PlayerForm(instance=player)
    if request.method == 'POST':
        form = PlayerForm(request.POST, instance=player)
        if form.is_valid():
            form.save()
            return redirect('playerTrainingSystem:manage_players')
    context = {'form': form}
    return render(request, 'player_form.html', context)

def deletePlayer(request, pk):
    """
    Deletes a player object from the database.

    :param request: The request object containing metadata about the request.
    :type request: HttpRequest
    :param pk: The unique identifier for the player object to be deleted.
    :type pk: int
    :return: A redirect to the manage_players view if the request method is POST,
             otherwise a render of the delete_player.html template.
    :rtype: HttpResponse
    """
    player = Player.objects.get(id=pk)
    if request.method == 'POST':
        player.delete()
        return redirect('playerTrainingSystem:manage_players')
    context = {'player': player}
    return render(request, 'delete_player.html', context)

playerTrainingSystem/templates/delete_player.html
{% extends "index.html" %}
{% block content %}
<div class="title">
    <h2>Remove Player</h2>
</div>
<p>Are you sure you want to remove {{player.first_name}} from the system?</p><br><br>
<form method="POST">
    {% csrf_token %}
    <a href="{% url 'playerTrainingSystem:manage_players' %}">Cancel</a><br><br><br><br>
    <input type="submit" class="submit" name="Confirm"><br><br>
</form>
{% endblock %}

playerTrainingSystem/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Al Try-eda SC</title>
    <style>
        #header{
            background: linear-gradient(rgba(0, 0, 0,  0.5), rgba(0, 0, 0, 0.3)), url("{% static 'images/coder.jpg' %}") center/cover no-repeat fixed;
            justify-content: flex-start;
            align-items: flex-end;
        }
        .submit{
        border: none;
        outline: none;
        height: 45px;
        width: 20%;
        background: #ececec;
        border-radius: 5px;
        transition: .4s;
        }
        .submit:hover{
            background-color: rgba(37, 95, 156, 0.9);
            color: #fff;
        }
    </style>
</head>
<body>
    <!-- header -->
    <section id="header" class="vh-100-flex">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="header-content">
                        <h1>Welcome Coach</h1>
                        <h1>You can <span class="typewrite" data-loop="yes" data-speed="100" data-delay="2000" data-words='["add a player to the system", "edit the details of the player", "remove the player from the system", "view players that are eligible for selection"]'></span></h1>
                        <h3>Al Try-eda Sporting Club</h3>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end of header -->

    <!-- main content -->
    <main>
        <!-- user option -->
        <section id="option" class="about py-7">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </section>
        <!-- end user option -->
    </main>
    <!-- footer -->
    <section id="header" class="vh-100-flex">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="header-content">
                        <center>
                            <h3>© 2023 Nhlosokuhle Bandile Khoza</h3>
                        </center>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end of header -->
    
    <!-- typewriting js -->
    <script src="{% static 'js/typewriting.js' %}">

    </script>
</body>
</html>

playerTrainingSystem/templates/manage_players.html
{% extends "index.html" %}
{% block content %}
    <div class="title">
        <h2>Manage Players</h2>
    </div>
    <div class="card card-body">
        <a class="btn btn-primary btn-sm btn-block" href="{% url 'playerTrainingSystem:create_player' %}">Add Player</a>
        <a class="btn btn-primary btn-sm btn-block" href="{% url 'playerTrainingSystem:eligible_players' %}">View players that are eligible for selection</a>
        <table class="table table-sm">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Skill Level</th>
                <th>Eligible for Selection</th>
                <th>Update</th>
                <th>Remove</th>
            </tr>
            {% for player in players %}
                <tr>
                    <td>{{player.first_name}}</td>
                    <td>{{player.last_name}}</td>
                    <td>{{player.skill_level}}</td>
                    <td>{{player.eligible_for_selection}}</td>     
                    <td><a class="btn btn-sm btn-info" href="{% url 'playerTrainingSystem:update_player' player.id %}">Update</a></td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'playerTrainingSystem:delete_player' player.id %}">Delete</a></td>              
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

playerTrainingSystem/templates/player_form.html
{% extends 'index.html' %}
{% block content %}
<div class="title">
    <h2>Player Information</h2>
</div>
<form method="POST">
    {% csrf_token %}
    {{form}} <br><br><br><br><br><br><br><br>
    <input type="submit" class="submit" value="Submit">
</form>
{% endblock %}

playerTrainingSystem/templates/view_players.html
{% extends "index.html" %}
{% block content %}
    <div class="title">
        <h2>Players who are eligible for selection in the upcoming game</h2>
    </div>
    <div class="card card-body">
        <a class="btn btn-primary btn-md btn-block" href="{% url 'playerTrainingSystem:manage_players' %}">Manage players</a>
        <table class="table table-md">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
            </tr>
            {% for player in players %}
                {% if player.skill_level > 14 %}
                <tr>
                    <td>{{player.first_name}}</td>
                    <td>{{player.last_name}}</td>          
                </tr>
                {% endif %}
            {% endfor %}
        </table>
    </div>
{% endblock %}