mySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_auth.urls', namespace='user_auth')),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls")),
    path('playerTrainingSystem/', include('playerTrainingSystem.urls', namespace='playerTrainingSystem')),
]

user_auth/urls.py
from django.urls import path, include
from . import views

app_name = 'user_auth'
urlpatterns = [
    path('user_login/', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('', views.register, name='register')
]

user_auth/models.py
from django.db import models

# Create your models here.

user_auth/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User, auth

# Create your views here.
def register(request):
    """
    Registers a new user.

    If the request method is POST, this function retrieves the user's first name, email, and password
    from the request.POST dictionary, creates a new user object with the retrieved data, saves the user
    object to the database, and then redirects the user to the 'manage_players' page. If the request
    method is not POST, this function simply renders the signup.html template.

    :param request: The HttpRequest object containing the user's registration data.
    :type request: HttpRequest

    :returns: If the request method is POST, this function returns an HttpResponseRedirect object
    that redirects the user to the 'manage_players' page. If the request method is not POST, this
    function returns an HttpResponse object that renders the signup.html template.
    :rtype: HttpResponse or HttpResponseRedirect
    """
    if request.method == 'POST':
        first_name = request.POST['username']
        username = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username=username, password=password, first_name=first_name)
        user.save()
        return HttpResponseRedirect(reverse('playerTrainingSystem:manage_players'))
    else:
        return render(request, 'signup.html')

def user_login(request):
    """
    Displays the login page.

    This function renders the signin.html template, which displays a form that allows the user to log in.

    :param request: The HttpRequest object for the current request.
    :type request: HttpRequest

    :return: The rendered HTML response for the signin.html template.
    :rtype: HttpResponse
    """
    return render(request, 'signin.html')

def authenticate_user(request):
    """
    Authenticates a user and logs them in.

    This function retrieves the user's username and password from the request.POST dictionary, then
    attempts to authenticate the user with those credentials. If the authentication is successful,
    the function logs the user in by calling the login() function with the HttpRequest object and the
    authenticated user object. The function then redirects the user to the 'manage_players' page.
    If the authentication is not successful, the function redirects the user to the 'login' page.

    :param request: The HttpRequest object containing the user's login credentials.
    :type request: HttpRequest

    :returns: An HttpResponseRedirect object that redirects the user to either the 'manage_players'
    page (if the authentication was successful) or the 'login' page (if the authentication was not
    successful).
    :rtype: HttpResponse
    """
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(reverse('user_auth:login'))
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('playerTrainingSystem:manage_players'))

user_auth/templates/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign in</title>
</head>
<body>
    <div class="wrapper">
        <div class="container main">
            <div class="row">
                <div class="col-md-6 side-image">
                    <!-- Image -->
                    <img src="{% static 'blank.png' %}" class="img-fluid" alt="">
                </div>
                <div class="col-md-6 right">
                    <div class="input-box">
                        <h1>PlayerTracker</h1>
                        <header>Sign in</header>
                        <form action="{% url 'user_auth:authenticate_user' %}" method="post">
                            {% csrf_token %}
                            <div class="input-field">
                                <input type="text" name="username" class="input" id="username" required autocomplete="off">
                                <label for="username">Username</label>
                            </div>
                            <div class="input-field">
                                <input type="password" name="password" class="input" id="password" required>
                                <label for="password">Password</label>
                            </div>
                            <div class="input-field">
                                <input type="submit" class="submit" value="Sign in">
                            </div>
                            <div class="signin">
                                <span>Don't have an account? <a href="/">Click here</a></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

user_auth/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign up</title>
</head>
<body>
    <div class="wrapper">
        <div class="container main">
            <div class="row">
                <div class="col-md-6 side-image">
                    <!-- Image -->
                    <img src="{% static 'blank.png' %}" class="img-fluid" alt="">
                </div>
                <div class="col-md-6 right">
                    <div class="input-box">
                        <h1>PlayerTracker</h1>
                        <header>Create account</header>
                        <form action="{% url 'user_auth:register' %}" method="post">
                            {% csrf_token %}
                            <div class="input-field">
                                <input type="text" name="username" class="input" id="username" required autocomplete="off">
                                <label for="username">Username</label>
                            </div>
                            <div class="input-field">
                                <input type="email" name="email" class="input" id="email" required autocomplete="off">
                                <label for="email">Email</label>
                            </div>
                            <div class="input-field">
                                <input type="password" name="password" class="input" id="password" required>
                                <label for="password">Password</label>
                            </div>
                            <div class="input-field">
                                <input type="submit" class="submit" value="Sign up">
                            </div>
                            <div class="signin">
                                <span>Already have an account? <a href="{% url 'user_auth:login' %}">Click here</a></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>